name: Build Docker image

on:
    push:
        branches: master
        tags:
            - v*
    pull_request:

env:
    DOCKER_IMAGE: mammo0/docker-arkime

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ env.DOCKER_IMAGE }}
                tags: |
                  type=edge,branch=master
                  type=ref,event=tag

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              if: ${{ github.event_name == 'push' }}
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              if: ${{ github.event_name == 'push' }}
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
